### ISSUE TITLE
TypeError: Cannot handle this data type: (1, 1, 48), |u1

### ISSUE THREAD

**Issue by rightlit** [rightlit/AttnGAN-rev#2]
Traceback (most recent call last):
  File "pretrain_DAMSM.py", line 274, in <module>
    dataset.ixtoword, image_dir)
  File "pretrain_DAMSM.py", line 125, in train
    ixtoword, attn_maps, att_sze)
  File "/content/AttnGAN/code/miscc/utils.py", line 148, in build_super_images
    PIL_att = Image.fromarray(np.uint8(one_map))
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2682, in fromarray
    raise TypeError("Cannot handle this data type: %s, %s" % typekey)
TypeError: Cannot handle this data type: (1, 1, 48), |u1

**Comment by rightlit** [comment]
https://stackoverflow.com/questions/60921298/np-array-to-pil-image-typerror-cannot-handle-this-data-type-1-1-12-u

=========================
I had same error like you. I found that this error occurred because one_map arrays once upsampled(or expanded) have different dimension of original arrays. 3rd dimension of array(eg. (1,1,12)) may need to be 3 dimension for RGB color channel.

So I had tried to find a way to upsample without expand 3rd dimension(eg. z-direction).

I finally got a solution and modified that code just adding parameter "multichannel=True (default is False)" in function skimage.transform.pyramid_expand(). my full code is as follows.

one_map = skimage.transform.pyramid_expand(one_map, sigma=20, upscale=vis_size // att_sze, multichannel=True)

I found that above code doesn't change 3rd dimension for color channel. please try this code if you run attngan from github.

=========================
The error I had is as follows.

Traceback (most recent call last):
File "pretrain_DAMSM.py", line 274, in
dataset.ixtoword, image_dir)
File "apretrain_DAMSM.py", line 125, in train
ixtoword, attn_maps, att_sze)
File "/content/AttnGAN/code/miscc/utils.py", line 148, in build_super_images
PIL_att = Image.fromarray(np.uint8(one_map))
File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2682, in fromarray
raise TypeError("Cannot handle this data type: %s, %s" % typekey)
TypeError: Cannot handle this data type: (1, 1, 48), |u1

**Comment by rightlit** [comment]
I had same error like you. I found that this error occurred because one_map arrays once upsampled(or expanded) have different dimension of original arrays. 3rd dimension of array(eg. (1,1,12)) may need to be 3 dimension for RGB color channel.

So I had tried to find a way to upsample without expand 3rd dimension(eg. z-direction).

I finally got a solution and modified that code just adding parameter "multichannel=True (default is False)" in function skimage.transform.pyramid_expand(). my full code is as follows.

one_map = skimage.transform.pyramid_expand(one_map, sigma=20, upscale=vis_size // att_sze, multichannel=True)

I found that above code doesn't change 3rd dimension for color channel. please try this code if you run attngan from github.

The error I had is as follows.

Traceback (most recent call last):
File "pretrain_DAMSM.py", line 274, in <module>
  dataset.ixtoword, image_dir)
File "apretrain_DAMSM.py", line 125, in train
  ixtoword, attn_maps, att_sze)
File "/content/AttnGAN/code/miscc/utils.py", line 148, in build_super_images
  PIL_att = Image.fromarray(np.uint8(one_map))
File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2682, in fromarray
  raise TypeError("Cannot handle this data type: %s, %s" % typekey)
TypeError: Cannot handle this data type: (1, 1, 48), |u1
